USERS = '''CREATE TABLE USERS (
    USER_ID        INTEGER  PRIMARY KEY,
    USER_NAME      TEXT     NOT NULL,
    USERNAME       TEXT     NOT NULL,
    SUBSCRIBER     BOOLEAN  DEFAULT TRUE,
    TOTAL_VALUE    REAL     DEFAULT 0.0,
    CHANGE_VALUE   REAL     DEFAULT 0.0,
    CHANGE_PERCENT REAL     DEFAULT 0.0,
    JOINED         DATETIME DEFAULT (DATETIME(('now'))));'''

ASSETS = '''CREATE TABLE ASSETS (
    COIN_NAME      TEXT,
    COIN_SYMBOL    TEXT    NOT NULL,
    PRICE          REAL    DEFAULT 0.0,
    AMOUNT         TEXT    DEFAULT 0.0,
    VALUE          REAL    DEFAULT 0.0,
    CHANGE_VALUE   REAL    DEFAULT 0.0,
    CHANGE_PERCENT REAL    DEFAULT 0.0,
    USER_ID        INTEGER NOT NULL,
    UNIQUE (
        COIN_SYMBOL,
        USER_ID
    ),
    FOREIGN KEY (
        USER_ID
    )
    REFERENCES USERS (USER_ID) ON DELETE CASCADE
);'''
